// Problem:
// Each new term in the Fibonacci sequence is generated by adding 
// the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed 
// four million, find the sum of the even-valued terms.


// Solution:

evenFibonacciSum = (max) => {
    let i = 2;
    let j = 3;
    let x;
    let arr = [];
    while (i < max) {
        if (i % 2 === 0) {
            arr.push(i);
        }
        x = i + j
        i = j
        j = x
    }

    return arr.reduce((acc, curVal) => acc + curVal);
};