# Problem:
# Each new term in the Fibonacci sequence is generated by adding 
# the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed 
# four million, find the sum of the even-valued terms.

def four_million_fibonacci()
  arr = [1, 2]
  num = 0
  even_sum = 2

  while num < 4000000 do
    num = arr[-1] + arr[-2]
    arr << num
    if num % 2 == 0 
      even_sum += num 
    end
  end

  puts even_sum
end

four_million_fibonacci()